<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Battuta.Core\Battuta.Core.csproj" />
    <ProjectReference Include="..\..\src\Battuta.Windows\Battuta.Windows.csproj" />
    <ProjectReference Include="..\Battuta.TestSupport\Battuta.TestSupport.csproj" />
  </ItemGroup>

</Project>
